CREATE TABLE USER_PROFILES (
  USER_NAME VARCHAR2(20) PRIMARY KEY, 
  DISPLAY_NAME VARCHAR2(30),
  DESCRIPTION VARCHAR2(50),
  GENDER VARCHAR2(10),
  AGE NUMBER(38),
  COUNTRY VARCHAR2(20),
  THEME VARCHAR2(30));
